export const circles = [
  {
    filter: 'blur(5px)',
    zIndex: -1,
    position: 'absolute',
    width: '106px',
    top: '10%',
    height: '196px',
    right: '15%',
  },
  {
    filter: 'blur(5px)',
    zIndex: -1,
    position: 'absolute',
    width: '75px',
    top: '25%',
    height: '196px',
    left: '10%',
  },
  {
    filter: 'blur(2px)',
    zIndex: -1,
    position: 'absolute',
    width: '75px',
    top: '28%',
    height: '20px',
    left: '5%',
  },
  {
    filter: 'blur(3px)',
    zIndex: -1,
    position: 'absolute',
    width: '75px',
    bottom: '8%',
    height: '50px',
    left: '15%',
  },
  {
    filter: 'blur(3px)',
    zIndex: -1,
    position: 'absolute',
    width: '75px',
    bottom: '8%',
    height: '55px',
    right: '25%',
  },
];
